Repository aviv82/aviv.home, pull requests merged in 2021-11, with the labels that each got.

#1 test pr
  README.md
  package-lock.json
Labels: test

#2 add 1st-interview.md
  pages/1st-interview.md
Labels: documentation

#4 Planning pages
  planning/1st-interview.md
  planning/backlog.md
  planning/communication.md
  planning/constraints.md
  planning/development-strategy.md
  planning/follow-up-interview.md
  planning/retrospective.md
Labels: documentation

#12 create user-persona
  .cspell.json
  planning/user-persona.md
Labels: documentation

#13 Update plan files
  planning/1st-interview.md
  planning/backlog.md
  planning/follow-up-interview.md
  planning/user-persona.md
Labels: documentation

#14 Webpage analysis
  assets/aviv-pa-1.png
  planning/1st-interview.md
  planning/webpage-analysis.md
Labels: documentation

#16 Webpage analysis
  assets/aviv-pa-2.png
  assets/aviv-pa-3.png
  planning/webpage-analysis.md
Labels: documentation

#17 Webpage wireframe
  assets/aviv-about.png
  assets/aviv-homepage.png
  assets/aviv-portfolio.png
  planning/webpage-analysis.md
Labels: documentation

#19 Create webpage-wireframe.md
  planning/webpage-wireframe.md
Labels: documentation

#20 Design retrospective
  planning/design-retrospective.md
  planning/retrospective.md
Labels: documentation

#21 edit development strategy
  planning/development-strategy.md
Labels: documentation

#36 create home intro
  index.html
  styles/style.css
Labels: html, css, must have

#37 create nav bar buttons
  index.html
  styles/style.css
Labels: html, css, must have

#38 intro section
  index.html
  styles/style.css
Labels: html, css, must have

#39 10 about me text
  index.html
  js/index.js
  styles/style.css
Labels: html, css, must have

#40 create footer form
  index.html
  styles/style.css
Labels: html, css, must have

#41 create development retrospective
  planning/development-retrospective.md
Labels: documentation

#44 Update CODE-OF-CONDUCT.md
  CODE-OF-CONDUCT.md
Labels: documentation

#45 Create info for contributors
  planning/contributors.md
Labels: documentation

#47 11 sm links
  CODE-OF-CONDUCT.md
  index.html
  js/index.js
  planning/contributors.md
  styles/style.css
Labels: html, css, must have

#48 adding readme
  planning/README.md
Labels: html, css, readme, ux/ui

#49 create portfolio skills
  .cspell.json
  README.md
  index.html
  js/index.js
  pages/portfolio.html
  planning/README.md
  styles/style.css
Labels: html, css, could have

#50 6 video section
  js/index.js
  pages/portfolio.html
  styles/style.css
Labels: html, css, could have

#52 video section on portfolio page
  index.html
  js/index.js
  pages/portfolio.html
  styles/style.css
Labels: html, css, could have
